apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*snowflake-id-generator*.log
      pos_file /var/log/fluentd-containers.pos
      tag kube.*
      read_from_head true
      <parse>
        @type json
      </parse>
    </source>

    <filter kube.**>
      @type kubernetes_metadata
    </filter>

    # Фильтр только для ID Generator
    <filter kube.**>
      @type grep
      <regexp>
        key $.kubernetes.labels.app
        pattern ^id-generator$
      </regexp>
    </filter>

    <filter kube.**>
      @type record_transformer
      enable_ruby true
      <record>
        log_only ${record["log"]}
      </record>
    </filter>

    <match kube.**>
      @type stdout
      <format>
        @type single_value
        message_key log_only
      </format>
    </match>
