apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-tls
  labels:
    app: {{ .Chart.Name }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.crt }}
  tls.key: {{ .Values.secrets.key }}
