apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}-secrets
stringData:
  POSTGRES_USER: {{ .Values.global.postgres.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.global.postgres.postgresPassword }}
