apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }} # Обнаружение связанного объекта Pod по его метке
  ports:
    - port: {{ .Values.global.postgres.postgresPort }}
      targetPort: {{ .Values.global.postgres.postgresPort }}
      protocol: TCP
#  type: None # Headless Service является обязательным для StatefulSet
